version: '3.7'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    environment:
      - CLUSTER_NAME=test
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - namenode:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    depends_on:
      - namenode
    volumes:
      - datanode:/hadoop/dfs/data

  hive:
    image: bde2020/hive:2.3.9-postgresql-metastore
    depends_on:
      - namenode
    environment:
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://metastore/metastore
    ports:
      - "10000:10000"

  spark:
    image: bitnami/spark:3
    environment:
      - SPARK_MODE=master
    ports:
      - "4040:4040"
      - "7077:7077"
    depends_on:
      - hive

  metastore:
    image: postgres:13
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive

volumes:
  namenode:
  datanode:
